# Generated by Django 6.0.6 on 2026-07-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('score', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('ai_risk_score', models.IntegerField()),
                ('ssl_title', models.TextField()),
                ('ssl_sub', models.TextField()),
                ('domain_age', models.TextField()),
                ('domain_sub', models.TextField()),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('google_safe', models.BooleanField(default=True)),
                ('location', models.TextField()),
                ('has_redirection', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
