# Generated by Django 6.0.6 on 2026-08-24 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0003_reclassify_scan_risk_levels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=253, unique=True)),
                ('scan_count', models.PositiveIntegerField(default=0)),
                ('unique_scanner_count', models.PositiveIntegerField(default=0)),
                ('report_count', models.PositiveIntegerField(default=0)),
                ('approved_report_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scanned_by', models.ManyToManyField(blank=True, related_name='scanned_domains', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='SuspiciousSiteReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253)),
                ('url', models.URLField(max_length=2048)),
                ('reason', models.CharField(choices=[('phishing', 'หลอกขโมยข้อมูล (Phishing)'), ('scam', 'หลอกลวง/ฉ้อโกง'), ('malware', 'อาจมีมัลแวร์หรือไฟล์อันตราย'), ('other', 'อื่น ๆ')], max_length=20)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'รอตรวจสอบ'), ('approved', 'อนุมัติแล้ว'), ('rejected', 'ปฏิเสธแล้ว')], db_index=True, default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_site_reports', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ('pending', 'approved'))), fields=('user', 'domain'), name='one_open_or_approved_report_per_user_domain')],
            },
        ),
    ]
