# Generated by Django 6.0.6 on 2026-10-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0009_alter_knowledgearticle_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgearticle',
            name='content_html',
            field=models.TextField(blank=True, default='', help_text='Sanitized HTML for safe rendering'),
        ),
        migrations.AlterField(
            model_name='knowledgearticle',
            name='content_markdown',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='knowledgearticle',
            name='image',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='knowledgearticle',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)'),
        ),
        migrations.AlterField(
            model_name='knowledgearticle',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='suspicioussitereport',
            name='reason',
            field=models.CharField(choices=[('phishing', 'Phishing / Credential Theft'), ('scam', 'Scam / Fraud'), ('malware', 'Malware / Dangerous File'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='suspicioussitereport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
    ]
