# Generated by Django 6.0.6 on 2026-08-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0005_knowledgearticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainstatistic',
            name='last_score',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='domainstatistic',
            name='last_status',
            field=models.CharField(blank=True, default='safe', max_length=20),
        ),
    ]
