# Generated by Django 5.2.16 on 2026-09-08 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0006_domainstatistic_last_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgearticle',
            name='content_html',
            field=models.TextField(blank=True, default='', help_text='HTML ที่ผ่านการ sanitize แล้ว'),
        ),
        migrations.AddField(
            model_name='knowledgearticle',
            name='content_markdown',
            field=models.TextField(blank=True, default='', help_text='Markdown ดิบตามที่แอดมินพิมพ์'),
        ),
    ]
