# Generated by Django 5.2.16 on 2026-09-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0007_knowledgearticle_content_html_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgearticle',
            name='image',
            field=models.CharField(blank=True, help_text='URL รูปภาพภายนอก หรือที่อยู่ไฟล์ที่อัปโหลด (/media/articles/...)', max_length=500),
        ),
    ]
