# Generated by Django 5.2.16 on 2026-09-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0008_alter_knowledgearticle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgearticle',
            name='content',
            field=models.JSONField(blank=True, default=dict, help_text='{"sections": [...], "key_takeaways": [...]}'),
        ),
    ]
